config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "static_pages#home"

  resources :gossips do
  	resources :comments, except: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :gossip, dependent: :destroy
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_and_belongs_to_many :tags
  has_many :comments
  has_many :likes 
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_and_belongs_to_many :gossips
end

app/models/user.rb
class User < ApplicationRecord
	has_many :likes
	has_many :gossips
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		Comment.create(content: params[:content], user_id: params[:user_id].to_i, gossip_id: params[:gossip_id].to_i)
		redirect_to(gossip_path(params[:gossip_id]))
	end

	def destroy
		Comment.find(params[:id]).delete
		redirect_to(gossip_path(params[:gossip_id]))
	end

	def edit
		@comment = Comment.find(params[:id].to_i)
		@user_number = User.all.count
		@gossip = Gossip.find(params[:gossip_id])
	end

	def update
		comment = Comment.find(params[:id])
		param_comment = params[:comment]

		comment.content = param_comment[:content]
		comment.user_id = param_comment[:user_id]
		comment.gossip_id = param_comment[:gossip_id]
		comment.save
		redirect_to(gossip_path(param_comment[:gossip_id]))
	end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
	def new
		@gossip = Gossip.new
		@user_number = User.all.count
	end

	def create
		param = params[:gossip]
		if param[:title] != "" && param[:content] != "" && param[:user_id] != ""
			new_gossip = accepte
			Gossip.create(new_gossip)
			redirect_to(gossips_path)

		else
			redirect_to(new_gossip_path)
		end
	end

	def index
		@gossips = Gossip.all	
	end

	def show
		@gossip = Gossip.find(params[:id].to_i)
		@Comment = Comment.new
		@user_number = User.all.count
	end

	def edit
		@gossip = Gossip.find(params[:id].to_i)
		@user_number = User.all.count
	end

	def update
		param = params[:gossip]
		@gossip = Gossip.find(params[:id].to_i)
		if param[:title] != "" && param[:content] != "" && param[:user_id] != ""
			edit_gossip = accepte
			@gossip.update(edit_gossip)
			redirect_to(gossip_path(@gossip.id))
		else
			redirect_to(edit_gossip_path(@gossip.id))
		end
	end

	def destroy
		@gossip = Gossip.find(params[:id].to_i)
		@gossip.delete
		redirect_to(gossips_path)
	end

private

def accepte
	params.require(:gossip).permit(:title, :content, :user_id)
end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/edit.html.erb
<div class="container">

<h3 class = "text-primary">Edit Comment</h3>

<%=form_with model: @comment, url: gossip_comment_path(@gossip.id, @comment.id) do |c| %>

	<p>Content</p>
	<%= c.text_field :content, class: "form-control" %></br>
	<p>User_id</p>
	<%= c.number_field :user_id, in: 1..@user_number, class: "form-control" %></br>
	<p>Gossip_id</p>
	<%= c.number_field :gossip_id, in: @gossip.id..@gossip.id, class: "form-control" %></br>

	</br><%= c.submit "Update comment", class: "btn btn-primary"%></br>


<% end %>

</div>

app/views/gossips/edit.html.erb
<div class="container">

<h1 class="text-danger">Page to edit the Gossip</h1>



<%= form_for @gossip, url: gossip_path, class: "form-group" do |f| %>
	<p>Title</p>
	<%= f.text_field :title, class: "form-control" %></br>
	<p>Content</p>
	<%= f.text_area :content, class: "form-control" %></br>
	<p>User_id</p>
	<%= f.number_field :user_id, in: 1..@user_number, class: "form-control" %></br>
	</br><button type='submit' class = 'btn btn-primary'>Update gossip</button>

<% end %>

</div>

app/views/gossips/index.html.erb
</br>
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Content</th>
      <th scope="col">User</th>
      <th scope="col">Comment</th>
    </tr>
  </thead>
  <tbody>
  	<% @gossips.each do |g| %>
    <tr>
      <td><%= g.title %></td>
      <td><%= g.content %></td>
      <td><%= g.user.name %></td>
      <td><%= g.comments.count %></td>
      <td><%= link_to "Page gossip", gossip_path(g.id), class: "btn btn-primary" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/gossips/new.html.erb
<div class="container">

<h1 class="text-danger">Page to create a new Gossip</h1>



<%= form_for @gossip, url: gossips_path, class: "form-group" do |f| %>
	<p>Title</p>
	<%= f.text_field :title, class: "form-control" %></br>
	<p>Content</p>
	<%= f.text_area :content, class: "form-control" %></br>
	<p>User_id</p>
	<%= f.number_field :user_id, in: 1..@user_number, class: "form-control" %></br>
	</br><button type='submit' class = 'btn btn-primary'>Create gossip</button>

<% end %>

</div>

app/views/gossips/show.html.erb
<div class = "container">

<h2>Vous etes sur la page du gossip n°<%= @gossip.id %> <%= link_to "Edit gossip", edit_gossip_path(@gossip.id), class: "btn btn-warning" %> <%= link_to 'Clique pour détruire', @gossip, method: :delete, class: "btn btn-danger" %></h2> </br>

<h4>Createur du gossip => <%= @gossip.user.name %></h4></br>
<h4>Titre du gossip => <%= @gossip.title %></h4></br>
<h4>Contenue du gossip => <%= @gossip.content %></h4></br>

<h4>Revenir à la page <%= link_to "index", gossips_path, class: "btn btn-primary" %> des gossips </h4>

<h2 class="text-primary">Commentaire</h2>



<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Content</th>
      <th scope="col">User</th>
    </tr>
  </thead>
  <tbody>
  	<% @gossip.comments.each do |c| %>
    <tr>
      <td><%= c.content %></td>
      <td><%= c.user.name %></td>
      <td><%= link_to "Edit", edit_gossip_comment_path(@gossip.id, c.id), class: "btn btn-success" %></td>
      <td><%= link_to 'Supp', gossip_comment_path(@gossip.id, c.id), method: :delete, class: "btn btn-danger" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<h3 class = "text-primary">New Comment</h3>

<%=form_with model: @comment, url: gossip_comments_path(@gossip.id) do |c| %>

	<p>Content</p>
	<%= c.text_field :content, class: "form-control" %></br>
	<p>User_id</p>
	<%= c.number_field :user_id, in: 1..@user_number, class: "form-control" %></br>
	<p>Gossip_id</p>
	<%= c.number_field :gossip_id, in: @gossip.id..@gossip.id, class: "form-control" %></br>

	</br><%= c.submit "New comment", class: "btn btn-primary"%></br>


<% end %>
	
</div>
</br><p>Franklin Hyriol</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <div class="container">
 <ul class="navbar-nav mr-auto">
        <li class="nav-item"><%= link_to "Accueil", root_path, class: "text-success" %></li>&nbsp
        <li class="nav-item"><%= link_to "Index des gossips",   gossips_path %></li>&nbsp
        <li class="nav-item"><%= link_to "Nouveau gossip", new_gossip_path, class: "text-warning" %></li><hr>
      </ul>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProjectFullCrud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render "/layouts/header" %>

    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les moussaillons 🎓
  </h3>
  <%= link_to "Enregistre-toi !", '#', class: "btn btn-lg btn-primary" %>
</div>